// Generated by CoffeeScript 1.9.2
var AppRegistry, NavigatorIOS, React, StyleSheet, Text, View, Welcome, reader, styles;

React = require('react-native');

Welcome = require('./components/welcome');

AppRegistry = React.AppRegistry, StyleSheet = React.StyleSheet, Text = React.Text, View = React.View, NavigatorIOS = React.NavigatorIOS;

reader = React.createClass({
  render: function() {
    return React.createElement(NavigatorIOS, {
      "initialRoute": {
        component: Welcome,
        title: 'Reader'
      },
      "style": styles.container
    });
  }
});

styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  }
});

AppRegistry.registerComponent('reader', function() {
  return reader;
});
